package com.will.cellseg;

import ij.IJ;
import ij.plugin.PlugIn;
import net.imagej.legacy.IJ1Helper;
import org.scijava.Context;
import org.scijava.command.CommandService;

public class CellSegmentation_IJ1_Batch implements PlugIn {

    @Override
    public void run(String arg) {
        IJ.log("[CellSegmentation IJ1 Batch] Starting...");
        IJ.log("[CellSegmentation IJ1 Batch] run() jar=" + getClass().getProtectionDomain().getCodeSource().getLocation());

        final Context context = IJ1Helper.getLegacyContext();
        final CommandService cs = context.service(CommandService.class);

        // The batch command owns its own Swing dialog, so skip the autogenerated SciJava one.
        cs.run(CellSegmentationCommand_Batch.class, false);
    }
}
